- name: Install Nginx (Debian/Ubuntu)
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure web root exists
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Deploy templated index.html
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
  notify: reload nginx

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

