---
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add Docker GPG apt key
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: "{{ docker_apt_key_path }}"
    mode: '0644'

- name: Add Docker apt repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "{{ docker_apt_repo }}\n"
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker CE packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  notify: restart docker


- name: Run hello-nginx demo container
  community.docker.docker_container:
    name: "{{ hello_container_name }}"
    image: "{{ hello_image }}"
    state: started
    restart_policy: always
    published_ports: "{{ hello_ports }}"
