- name: Ensure required tooling is present
  hosts: dbservers
  become: yes
  tasks:
    - name: Ensure psycopg2 is installed
      package:
        name: python3-psycopg2
        state: present

    - name: Install acl package
      package:
        name: acl
        state: present


- name: Configure PostgreSQL root password
  hosts: dbservers
  become: yes
  tasks:
    - name: Ensure PostgreSQL is installed
      package:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Set postgres user password
      become_user: postgres
      postgresql_user:
        name: postgres
        password: "{{ postgres_root_password }}"
        role_attr_flags: SUPERUSER

